### ISSUE TITLE
online inference error using netG_100.pth

### ISSUE THREAD

**Issue by victorzhucompass** [S-aiueo32/srntt-pytorch#9]
[Feature swapping] done in 3247.264 ms
Traceback (most recent call last):
  File "online_inference.py", line 103, in <module>
    main(parse_args())
  File "online_inference.py", line 84, in main
    model.load_state_dict(torch.load(args.weight))
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SRNTT:
	Unexpected key(s) in state_dict: "texture_transfer.a", "texture_transfer.b".

**Comment by victorzhucompass** [comment]
with --use_wights it worked
